method=random
tiles=1 2 3 4 ./extra/1.png ./extra/2.png ./extra/3.png ./extra/7.png ./extra/8.png ./extra/9.png
weights=1 1 1 1 2 2 2 2 2 2
symmetry=opposite
linked=true
matchTiles=large_fern_top