tiles=1 17 33 49
weights=3 3 16 2
method=random
matchTiles=gravel
heights=0-68
biomes=ocean deep_ocean frozen_ocean deep_frozen_ocean cold_ocean deep_cold_ocean lukewarm_ocean deep_lukewarm_ocean warm_ocean beach