tiles=1-18
method=repeat
height=3
width=6
matchTiles=red_nether_bricks
matchBlocks=red_nether_brick_slab red_nether_brick_stairs
biomes=!nether_wastes crimson_forest warped_forest soul_sand_valley basalt_deltas