tiles=1-12 ./0_duckweed/1.png ./0_duckweed/2.png ./0_duckweed/3.png ./0_duckweed/4.png ./0_duckweed/5.png ./0_duckweed/6.png ./0_duckweed/7.png ./0_duckweed/8.png ./0_duckweed/9.png ./0_duckweed/10.png ./0_duckweed/11.png ./0_duckweed/12.png ./0_duckweed/13.png ./0_duckweed/14.png ./0_duckweed/15.png ./0_duckweed/16.png
weights=1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
method=random
symmetry=opposite
biomes=swamp
matchTiles=lily_pad