tiles=1 optifine/ctm/patrix/cobblestone/default/1.png 1 optifine/ctm/patrix/cobblestone/default/1.png optifine/ctm/patrix/cobblestone/default/1.png
method=ctm_compact
matchTiles=cobblestone
matchBlocks=cobblestone_slab:type=double
connect=tile
faces=sides