tiles=optifine/ctm/patrix/ice/default/1.png
method=fixed
matchTiles=dripstone_block
matchBlocks=pointed_dripstone
biomes=snowy_taiga snowy_plains ice_spikes snowy_beach frozen_river frozen_ocean deep_frozen_ocean grove snowy_slopes jagged_peaks frozen_peaks