method=random
tiles=21-24
symmetry=all
linked=true
matchTiles=textures/block/extra/large_fern_bottom_extra.png
biomes=savanna savanna_plateau windswept_savanna desert badlands eroded_badlands wooded_badlands