tiles=optifine/ctm/patrix/blackstone/stone/1.png optifine/ctm/patrix/blackstone/stone/17.png
method=random
matchTiles=dripstone_block
matchBlocks=pointed_dripstone
biomes=nether_wastes crimson_forest warped_forest soul_sand_valley basalt_deltas deep_dark