tiles=1-16
method=repeat
height=4
width=4
matchTiles=dark_oak_planks
faces=sides bottom
heights=0-63
biomes=ocean deep_ocean frozen_ocean deep_frozen_ocean cold_ocean deep_cold_ocean lukewarm_ocean deep_lukewarm_ocean warm_ocean beach stony_shore