tiles=1 37
method=random
matchTiles=brown_terracotta light_gray_terracotta orange_terracotta red_terracotta white_terracotta yellow_terracotta terracotta
matchBlocks=brown_terracotta light_gray_terracotta orange_terracotta red_terracotta white_terracotta yellow_terracotta terracotta
biomes=badlands eroded_badlands wooded_badlands