tiles=optifine/ctm/patrix/table/cartography/shelves/1.png optifine/ctm/patrix/table/cartography/shelves/1.png optifine/ctm/patrix/table/cartography/shelves/1.png 1
method=vertical
matchTiles=cartography_table_side2