tiles=1-4
method=random
matchTiles=scaffolding_side
matchBlocks=scaffolding
biomes=plains sunflower_plains swamp dark_forest forest flower_forest old_growth_birch_forest birch_forest meadow old_growth_pine_taiga taiga old_growth_spruce_taiga windswept_hills windswept_forest windswept_gravelly_hills stony_shore snowy_taiga snowy_plains ice_spikes snowy_beach frozen_river frozen_ocean deep_frozen_ocean grove snowy_slopes jagged_peaks frozen_peaks