tiles=1-8
method=random
matchTiles=end_stone_bricks
matchBlocks=end_stone_brick_slab end_stone_brick_stairs end_stone_brick_wall
biomes=!the_end small_end_islands end_midlands end_highlands end_barrens the_void