method=random
tiles=5 6 7 8 ./extra/4.png ./extra/5.png ./extra/6.png ./extra/10.png ./extra/11.png ./extra/12.png
weights=1 1 1 1 2 2 2 2 2 2
symmetry=opposite
linked=true
matchTiles=large_fern_bottom