method=random
tiles=1 ./extra/2.png ./extra/1.png ./extra/2.png 9 9 9 9 9 9 9 9 9 9 9 9 2 ./extra/4.png ./extra/3.png ./extra/4.png 9 9 9 9 9 9 9 9 9 9 9 9
weights=2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1
symmetry=all
linked=true
matchTiles=large_fern_top
biomes=dark_forest jungle bamboo_jungle sparse_jungle swamp mangrove_swamp