tiles=1-4
method=overlay_random
layer=cutout_mipped
matchTiles=stone cobblestone stone_bricks mossy_stone_bricks cracked_stone_bricks chiseled_stone_bricks
matchBlocks=infested_stone infested_cobblestone infested_stone_bricks infested_mossy_stone_bricks infested_cracked_stone_bricks infested_chiseled_stone_bricks