method=random
tiles=1-4 9-12 17-20 25-28 1-4 9-12 17-20 25-28
weights=2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1
symmetry=all
linked=true
matchTiles=textures/block/extra/large_fern_top_extra.png
biomes=dark_forest jungle bamboo_jungle sparse_jungle swamp mangrove_swamp