method=random
tiles=5-8 13-16 21-24 29-32 5-8 13-16 21-24 29-32
weights=2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1
symmetry=all
linked=true
matchTiles=textures/block/extra/large_fern_bottom_extra.png
biomes=dark_forest jungle bamboo_jungle sparse_jungle swamp mangrove_swamp