tiles=1-4
method=random
symmetry=opposite
matchTiles=textures/block/extra/dark_oak_leaves_extra.png
biomes=stony_peaks jungle bamboo_jungle sparse_jungle mushroom_fields plains sunflower_plains beach swamp mangrove_swamp dripstone_caves deep_dark dark_forest forest flower_forest old_growth_birch_forest birch_forest lush_caves cold_ocean deep_cold_ocean deep_frozen_ocean deep_lukewarm_ocean deep_ocean lukewarm_ocean ocean river warm_ocean