tiles=1-16
method=repeat
height=4
width=4
matchTiles=light_gray_wool
biomes=meadow old_growth_pine_taiga taiga old_growth_spruce_taiga windswept_forest windswept_gravelly_hills windswept_hills stony_shore snowy_beach snowy_plains ice_spikes frozen_river frozen_ocean grove snowy_slopes snowy_taiga jagged_peaks frozen_peaks